apiVersion: v1 
kind: ResourceQuota
metadata:
  name: ns-quotas
  namespace: dev 
spec:
  hard:
    limits.memory: "10Gi"
    limits.cpu: 5
    requests.memory: "3Gi"
    requests.cpu: 3
    services.loadbalancers: 5
    services.nodeports: 10
    persistentvolumeclaims: 10
    secrets: 10
    configmaps: 10
    pods: 20