apiVersion: v1 
kind: ServiceAccount
type: kubernetes.io/service-account-token
metadata:
  name: dev-sa-deployment
  namespace: dev 
  annotations:
    kubernetes.io/service-account.name: "dev-sa-deployment"
