apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret  
metadata:
  name: payments-db-secret
  namespace: payment 
spec:
  refreshInterval: 15m
  secretStoreRed:
    name: aws-secretmanager
    kind: SecretStore
  target:
    name: payments-db-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: prod/payment/db
      property: username 
  - secretKey: password
    remoteRef:
      key: prod/payment/db
      property: password
  - secretKey: host
    remoteRef:
      key: prod/payment/db
      property: host 

      #external-secret.yaml
      #kubectl get externalsecret -n payment

      