apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-rbac-crb
subjects:
- kind: Group 
  name: admin-team
  apiGroup: rbac.authorization.k8s.io
roleRef:
- kind: ClusterRole
  name: admin-rbac
  apiGroup: rbac.authorization.k8s.io
