apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-webapp
  namespace: dev 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app-ui
      version: v1.0.0
  template:
    metadata:
      labels:
        app: web-app-ui
        version: v1.0.0
    spec:
    #podsecuritycontext gives privelege to controll access to all containers in pod.
      securityCOntext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        runAsNonRoot: true #all containers in the pod will obey this security context.
      containers:
      - name: myapp
        image: vinayjadhav/java-app:v1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        securityCOntext:
          #for this container it will use this securitycontext as addon
          allowPrivelegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
      imagePullSecrets:
      - name: reg-cred
